# Generated by Django 4.1.7 on 2023-04-23 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.adverts.models.ad
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(verbose_name='Advertised URL')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Start showing')),
                ('publication_date_end', models.DateTimeField(default=modules.adverts.models.ad.now_plus_1_day, verbose_name='Stop showing')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('weight', models.IntegerField(default=1, help_text='Weight of the ad relative to other ads in the same zone.<br/>Ad with higher weight will be displayed more frequently.', verbose_name='Weight')),
                ('target_blank', models.BooleanField(default=False, verbose_name='Open in new tab')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('website', models.URLField(verbose_name='Company Site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='AdMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(choices=[('xs', 'Extra small devices'), ('sm', 'Small devices'), ('md', 'Medium devices (Tablets)'), ('lg', 'Large devices (Desktops)'), ('xl', 'Extra large devices (Large Desktops)')], max_length=2, verbose_name='Device')),
                ('image', versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='', verbose_name='Image')),
                ('media', models.FileField(blank=True, help_text='Please only Upload webm or mp4 for video files<br> And mp3 or wav for audio files', max_length=255, null=True, upload_to='', verbose_name='Media')),
                ('is_audio', models.BooleanField(default=False)),
                ('is_media', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='adverts.ad', verbose_name='Ad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('xs', 'Extra small devices'), ('sm', 'Small devices'), ('md', 'Medium devices (Tablets)'), ('lg', 'Large devices (Desktops)'), ('xl', 'Extra large devices (Large Desktops)')], max_length=2, verbose_name='Device')),
                ('image', versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='', verbose_name='Image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adverts.ad', verbose_name='Ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advertiser', verbose_name='Ad Provider'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP Address')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Session ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='adverts.ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
                'index_together': {('ad', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP Address')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Session ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='adverts.ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ad Click',
                'verbose_name_plural': 'Ad Clicks',
                'index_together': {('ad', 'session_id')},
            },
        ),
    ]
