# Generated by Django 4.0.3 on 2022-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
