# Generated by Django 4.0.3 on 2022-08-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_users_referral_code_users_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('human', 'Human')], default='human', max_length=100),
        ),
    ]
