# Generated by Django 4.0.3 on 2022-08-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users_referral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='referral',
            new_name='ref_code',
        ),
    ]
