# Generated by Django 4.0.3 on 2022-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_referral_users_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending Submission'), ('verification', 'Pending Verification'), ('approved', 'Approved'), ('declined', 'Declined')], default='active', max_length=100),
        ),
    ]
