# Generated by Django 4.1.7 on 2023-03-11 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_sponsors_expire_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsors",
            name="expire_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 10, 15, 37, 13, 753400),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="sponsors",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsor",
                to="subscriptions.packages",
            ),
        ),
    ]
