# Generated by Django 4.1.7 on 2023-03-11 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_sponsors_expire_at_alter_sponsors_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsors",
            name="expire_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 10, 15, 46, 35, 856030),
                editable=False,
            ),
        ),
    ]
