# Generated by Django 4.1.7 on 2023-03-27 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_packages_slug_alter_sponsors_expire_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsors",
            name="expire_at",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 26, 19, 6, 1, 751021), editable=False
            ),
        ),
    ]
