# Generated by Django 4.1.7 on 2023-04-24 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_sponsors_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='expire_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 25, 1, 41, 48, 33261), editable=False),
        ),
    ]
