# Generated by Django 4.1.7 on 2023-04-25 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_sponsors_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='expire_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 25, 17, 2, 57, 232082), editable=False),
        ),
    ]
