# Generated by Django 4.1.7 on 2023-05-23 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_sponsors_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='expire_at',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 9, 50, 45, 814388), editable=False),
        ),
    ]
