# Generated by Django 4.1.7 on 2023-06-06 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_alter_sponsors_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='expire_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 11, 4, 28, 50689), editable=False),
        ),
    ]
