# Generated by Django 4.1.7 on 2023-07-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_alter_sponsors_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
