# Generated by Django 4.0.3 on 2022-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_bookmarks_bookmark_rename_chapters_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='authors',
        ),
        migrations.AddField(
            model_name='stories',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='authors', to='stories.author'),
        ),
    ]
