# Generated by Django 4.0.3 on 2022-04-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='abbreviation',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
