# Generated by Django 4.0.3 on 2022-04-27 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0003_chapters_slug_stories_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='characters',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='genres',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='languages',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(choices=[('abandoned', 'Abandoned'), ('complete', 'Complete'), ('haitus', 'Haitus'), ('prerelease', 'Pre-Released'), ('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='types',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='universes',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
    ]
