# Generated by Django 4.0.3 on 2022-05-24 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_stories_authors_alter_bookmarks_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='story_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stories',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='story_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stories',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='story_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
