# Generated by Django 4.0.3 on 2022-06-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_stories_dislikes_stories_following_stories_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(choices=[('abandoned', 'Abandoned'), ('complete', 'Complete'), ('haitus', 'Haitus'), ('prerelease', 'Pre-Released'), ('published', 'Published'), ('oneshot', 'One Shot'), ('ongoing', 'Ongoing'), ('draft', 'Draft')], default='draft', max_length=100),
        ),
    ]
