# Generated by Django 4.1.7 on 2023-04-23 07:52

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycs',
            name='selfie',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=2048, null=True, upload_to=''),
        ),
    ]
