# Generated by Django 4.0.3 on 2022-04-12 22:04

import arrow.api
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the category Name', max_length=200)),
                ('slug', models.SlugField(default='name')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Unpublished', 'Not Published')], default='Draft', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.CharField(auto_created=True, blank=True, max_length=255, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', ckeditor.fields.RichTextField(blank=True, max_length=255, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Unpublished', 'Not Published')], default='Draft', max_length=100)),
                ('featured_image', models.CharField(blank=True, max_length=255, null=True)),
                ('featured_image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=36)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=arrow.api.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts_tags', to='blog.tags')),
                ('topics', models.ManyToManyField(blank=True, related_name='posts_topics', to='blog.topics')),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'unique_together': {('slug', 'user_id')},
            },
        ),
    ]
