# Generated by Django 4.1.7 on 2023-06-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modules.stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=modules.stats.models._default_uuid, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('origins', models.TextField(default='*', verbose_name='origins')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived')], db_index=True, default='AC', max_length=2, verbose_name='status')),
                ('respect_dnt', models.BooleanField(default=True, verbose_name='Respect dnt')),
                ('ignore_robots', models.BooleanField(default=False, verbose_name='Ignore robots')),
                ('collect_ips', models.BooleanField(default=True, verbose_name='Collect ips')),
                ('ignored_ips', models.TextField(blank=True, default='', validators=[modules.stats.models._validate_network_list], verbose_name='Igored ips')),
                ('hide_referrer_regex', models.TextField(blank=True, default='', validators=[modules.stats.models._validate_regex], verbose_name='Hide referrer regex')),
                ('script_inject', models.TextField(blank=True, default='', verbose_name='Script inject')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_services', to=settings.AUTH_USER_MODEL, verbose_name='Collaborators')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name', 'uuid'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=modules.stats.models._default_uuid, primary_key=True, serialize=False)),
                ('identifier', models.TextField(blank=True, db_index=True, verbose_name='Identifier')),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Start time')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last seen')),
                ('user_agent', models.TextField(verbose_name='User agent')),
                ('browser', models.TextField(verbose_name='Browser')),
                ('device', models.TextField(verbose_name='Device')),
                ('device_type', models.CharField(choices=[('PHONE', 'Phone'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('ROBOT', 'Robot'), ('OTHER', 'Other')], default='OTHER', max_length=7, verbose_name='Device type')),
                ('os', models.TextField(verbose_name='OS')),
                ('ip', models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP')),
                ('asn', models.TextField(blank=True, verbose_name='Asn')),
                ('country', models.TextField(blank=True, verbose_name='Country')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('time_zone', models.TextField(blank=True, verbose_name='Time zone')),
                ('is_bounce', models.BooleanField(db_index=True, default=True, verbose_name='Is bounce')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.BooleanField(db_index=True, default=True)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('heartbeats', models.IntegerField(default=0)),
                ('tracker', models.TextField(choices=[('BACK', 'Backend'), ('API', 'Api (noscript)')])),
                ('location', models.TextField(blank=True, db_index=True)),
                ('referrer', models.TextField(blank=True, db_index=True)),
                ('load_time', models.FloatField(db_index=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.service')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Hit',
                'verbose_name_plural': 'Hits',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', '-start_time'], name='stats_sessi_service_ab3261_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', '-last_seen'], name='stats_sessi_service_1ba9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', 'identifier'], name='stats_sessi_service_23a836_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', '-start_time'], name='stats_hit_session_9c4763_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['service', '-start_time'], name='stats_hit_service_4ebf72_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', 'location'], name='stats_hit_session_43667f_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', 'referrer'], name='stats_hit_session_0ad126_idx'),
        ),
    ]
