# Generated by Django 4.1.7 on 2023-07-20 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stats", "0002_alter_hit_tracker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="collaborators",
        ),
        migrations.RemoveField(
            model_name="service",
            name="owner",
        ),
        migrations.AddField(
            model_name="service",
            name="content_type",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
