# Generated by Django 4.1.7 on 2023-05-23 05:50

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
