from module.stories.models.author import *
from stories.models.bookmark import *
from stories.models.categories import *
from stories.models.chapter import *
from stories.models.character import *
from stories.models.editor import *
from stories.models.genre import *
from stories.models.history import *
from stories.models.language import *
from stories.models.rating import *
from stories.models.review import *
from stories.models.stories import *
from stories.models.type import *
from stories.models.universe import *
