# Generated by Django 4.1.2 on 2023-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stories",
            name="status",
            field=models.CharField(
                choices=[
                    ("abandoned", "Abandoned"),
                    ("complete", "Complete"),
                    ("hiatus", "Hiatus"),
                    ("prerelease", "Pre-Released"),
                    ("published", "Published"),
                    ("oneshot", "One Shot"),
                    ("ongoing", "Ongoing"),
                    ("draft", "Draft"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
    ]
