# Generated by Django 4.1.2 on 2022-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
