# Generated by Django 4.1.7 on 2023-03-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.stories.models.include


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0003_alter_stories_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translator",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translator_stories",
                        to="stories.stories",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translator_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "translators",
            },
            bases=(modules.stories.models.include.CacheInvalidationMixin, models.Model),
        ),
        migrations.AddField(
            model_name="stories",
            name="translator",
            field=models.ManyToManyField(
                blank=True,
                related_name="translators",
                through="stories.Translator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
